"""Click + rich command-line interface for vulnscan."""

from __future__ import annotations

import os
import stat
import sys
from dataclasses import dataclass, field
from pathlib import Path

import click
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text

from . import __version__
from .analyzer import (
    DEFAULT_MODEL,
    Analyzer,
    AnalyzerError,
    AuthError,
    FileReport,
    Finding,
)
from .formats import to_json, to_markdown, to_sarif
from .gitdiff import DiffInfo, GitError, diff_info, repo_root_for
from .prefilter import PrefilterResult, run_semgrep, semgrep_available
from .scanner import (
    LANGUAGE_BY_EXTENSION,
    SKIP_DIRECTORIES,
    MAX_FILE_BYTES,
    SourceFile,
    discover,
    language_for,
)

SEVERITY_ORDER = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3}

SEVERITY_BADGE_STYLE = {
    "CRITICAL": "white on red",
    "HIGH": "bold red",
    "MEDIUM": "bold yellow",
    "LOW": "bold cyan",
}

ORIGIN_LABEL = {
    "semgrep": ("semgrep lead", "magenta"),
    "independent": ("independent", "blue"),
}

# Sentinel returned by Click when --diff is passed with no value.
DIFF_DEFAULT_SENTINEL = "__VULNSCAN_DIFF_DEFAULT__"

OUTPUT_FORMATS = ("terminal", "json", "sarif", "markdown")

HOOK_SCRIPT = """#!/bin/sh
# vulnscan pre-commit hook (auto-generated by `vulnscan --install-hook`).
#
# Blocks the commit on CRITICAL findings by default. Override the threshold by
# exporting VULNSCAN_BLOCK_SEVERITY=HIGH (or CRITICAL) before committing, or by
# editing this file directly.
#
# Bypass for a single commit with: git commit --no-verify

set -e

BLOCK="${VULNSCAN_BLOCK_SEVERITY:-CRITICAL}"

# If vulnscan isn't installed, surface a clear error instead of silently passing.
if ! command -v vulnscan >/dev/null 2>&1; then
    printf 'vulnscan pre-commit hook: `vulnscan` is not on PATH; skipping.\\n' >&2
    exit 0
fi

exec vulnscan --diff --staged --block-on "$BLOCK"
"""

console = Console()


@dataclass
class RunStats:
    files_scanned: int = 0
    files_flagged_by_semgrep: int = 0
    files_sent_to_api: int = 0
    api_request_count: int = 0
    prefilter_active: bool = False
    prefilter_note: str | None = None
    diff_mode_note: str | None = None
    # Outcome counts — set after the scan loop completes.
    files_analyzed: int = 0   # API call + parse succeeded
    files_failed: int = 0     # API/parse error (results incomplete)
    files_skipped: int = 0    # not sent to API (prefilter or unreadable)


def _banner() -> None:
    title = Text("vulnscan", style="bold magenta")
    title.append(f"  v{__version__}", style="dim")
    subtitle = Text(
        "Defensive source-code security auditor (Anthropic-powered).",
        style="dim italic",
    )
    body = Text.assemble(title, "\n", subtitle)
    console.print(Panel(body, border_style="magenta", expand=False))


def _severity_badge(severity: str) -> Text:
    style = SEVERITY_BADGE_STYLE.get(severity, "white")
    return Text(f" {severity} ", style=style)


def _origin_tag(origin: str) -> Text:
    label, style = ORIGIN_LABEL.get(origin, (origin, "white"))
    return Text(f"[{label}]", style=style)


def _render_finding(finding: Finding) -> None:
    header = Text.assemble(
        _severity_badge(finding.severity),
        "  ",
        Text(finding.title, style="bold"),
        "  ",
        _origin_tag(finding.source),
    )
    if finding.pre_existing:
        header.append("  ")
        header.append("[pre-existing (outside this diff)]", style="dim yellow")
    if finding.lines:
        header.append(f"   (lines {finding.lines})", style="dim")
    console.print(header)
    if finding.explanation:
        console.print(Text.assemble(Text("  Why:  ", style="bold"), finding.explanation))
    if finding.remediation:
        console.print(
            Text.assemble(
                Text("  Fix:  ", style="bold green"),
                Text(finding.remediation, style="green"),
            )
        )
    console.print()


def _render_file_report(report: FileReport) -> None:
    if report.error and not report.findings:
        console.print(
            Panel(
                Text.assemble(
                    Text(str(report.source.path), style="bold"),
                    Text(f"  [{report.source.language}]", style="dim"),
                    "\n",
                    Text(report.error, style="red"),
                ),
                border_style="red",
                expand=False,
            )
        )
        return

    if not report.findings and not report.dismissed_leads:
        return

    header_text = Text.assemble(
        Text(str(report.source.path), style="bold"),
        Text(f"  [{report.source.language}]", style="dim"),
    )
    if report.had_leads:
        header_text.append("  [semgrep-prefiltered]", style="dim magenta")
    console.print(Panel(header_text, border_style="cyan", expand=False))

    sorted_findings = sorted(
        report.findings,
        key=lambda f: (SEVERITY_ORDER.get(f.severity, 99), f.pre_existing),
    )
    for finding in sorted_findings:
        _render_finding(finding)

    if report.dismissed_leads:
        console.print(Text("  Dismissed Semgrep leads:", style="dim italic"))
        for dismissed in report.dismissed_leads:
            console.print(
                Text.assemble(
                    Text("    - ", style="dim"),
                    Text(dismissed.rule, style="dim magenta"),
                    Text(f" (lines {dismissed.lines}): ", style="dim"),
                    Text(dismissed.justification, style="dim"),
                )
            )
        console.print()


def _render_summary(reports: list[FileReport], stats: RunStats) -> dict[str, int]:
    counts: dict[str, int] = {sev: 0 for sev in SEVERITY_ORDER}
    counts_new: dict[str, int] = {sev: 0 for sev in SEVERITY_ORDER}
    files_with_findings = 0
    for report in reports:
        if report.findings:
            files_with_findings += 1
        for finding in report.findings:
            counts[finding.severity] = counts.get(finding.severity, 0) + 1
            if not finding.pre_existing:
                counts_new[finding.severity] = counts_new.get(finding.severity, 0) + 1

    table = Table(title="Scan summary", border_style="magenta", show_lines=False)
    table.add_column("Severity", style="bold")
    table.add_column("Count", justify="right")
    if stats.diff_mode_note:
        table.add_column("In this diff", justify="right")
    for severity in ("CRITICAL", "HIGH", "MEDIUM", "LOW"):
        style = SEVERITY_BADGE_STYLE.get(severity, "white")
        row = [Text(severity, style=style), str(counts.get(severity, 0))]
        if stats.diff_mode_note:
            row.append(str(counts_new.get(severity, 0)))
        table.add_row(*row)
    console.print(table)

    total = sum(counts.values())
    files_analyzed = stats.files_analyzed
    files_failed = stats.files_failed
    analyzed_of_api = files_analyzed + files_failed
    console.print(
        f"Scanned {stats.files_scanned} file(s); {files_with_findings} with findings; "
        f"{total} finding(s) total."
    )
    if files_failed:
        if files_analyzed == 0:
            console.print(
                f"[bold red]ERROR: All {files_failed} file(s) failed to analyze. "
                f"No valid results are available — results are inconclusive.[/bold red]"
            )
        else:
            console.print(
                f"[bold yellow]WARNING: {files_failed}/{analyzed_of_api} file(s) failed "
                f"to analyze. Results are incomplete and may be missing vulnerabilities."
                f"[/bold yellow]"
            )
    if stats.diff_mode_note:
        console.print(f"[dim]{stats.diff_mode_note}[/dim]")
    if stats.prefilter_active:
        skipped = stats.files_scanned - stats.files_sent_to_api
        console.print(
            f"[dim]Semgrep prefilter: {stats.files_flagged_by_semgrep} flagged → "
            f"{stats.files_sent_to_api} sent to deep-reasoning pass "
            f"({skipped} skipped). "
            f"Anthropic API calls made: {stats.api_request_count}.[/dim]"
        )
    else:
        note = stats.prefilter_note or "Semgrep prefilter disabled."
        console.print(
            f"[dim]{note} Anthropic API calls made: {stats.api_request_count}.[/dim]"
        )
    return counts_new if stats.diff_mode_note else counts


def _prefilter_decision(
    path: Path,
    use_prefilter: bool,
) -> tuple[bool, PrefilterResult | None, str | None]:
    if not use_prefilter:
        return False, None, "Semgrep prefilter disabled by --no-prefilter."
    if not semgrep_available():
        return False, None, (
            "Semgrep binary not found on PATH — falling back to whole-file scan. "
            "Install with `pipx install semgrep` to enable prefiltering."
        )
    result = run_semgrep(path)
    if not result.available:
        return False, None, (
            "Semgrep prefilter unavailable (binary disappeared at runtime) — "
            "falling back to whole-file scan."
        )
    if result.error == "timeout":
        return False, result, "Semgrep timed out — falling back to whole-file scan."
    return True, result, None


def _is_scannable(path: Path) -> bool:
    if language_for(path) is None:
        return False
    parts = set(path.parts)
    return parts.isdisjoint(SKIP_DIRECTORIES)


def _diff_sources(info: DiffInfo) -> list[SourceFile]:
    """Read just the changed files into SourceFile objects, applying scanner filters."""
    sources: list[SourceFile] = []
    for path in info.changed_files:
        if not path.exists() or not path.is_file():
            continue
        if not _is_scannable(path):
            continue
        try:
            if path.stat().st_size > MAX_FILE_BYTES:
                continue
            content = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        language = language_for(path) or "Unknown"
        sources.append(SourceFile(path=path, language=language, content=content))
    return sources


def _install_pre_commit_hook(target: Path) -> int:
    """Write .git/hooks/pre-commit. Returns a process exit code."""
    repo = repo_root_for(target)
    if repo is None:
        console.print(
            "[bold red]Error:[/bold red] not inside a git repository — "
            "run --install-hook from within a repo."
        )
        return 2
    hooks_dir = repo / ".git" / "hooks"
    try:
        hooks_dir.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        console.print(f"[bold red]Error:[/bold red] cannot create {hooks_dir}: {exc}")
        return 2
    hook_path = hooks_dir / "pre-commit"
    if hook_path.exists():
        console.print(
            f"[yellow]A pre-commit hook already exists at {hook_path}.[/yellow]\n"
            f"[yellow]Refusing to overwrite — inspect it, then delete or merge by hand.[/yellow]"
        )
        return 1
    hook_path.write_text(HOOK_SCRIPT, encoding="utf-8", newline="\n")
    try:
        current = hook_path.stat().st_mode
        hook_path.chmod(current | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except OSError:
        pass  # On Windows the executable bit is informational; git runs the script anyway.
    console.print(
        Panel(
            Text.assemble(
                Text("Installed pre-commit hook at\n", style="bold green"),
                Text(str(hook_path), style="green"),
                Text(
                    "\n\nThe hook runs `vulnscan --diff --staged --block-on $VULNSCAN_BLOCK_SEVERITY`."
                    "\nDefault block threshold: CRITICAL.  Bypass once: `git commit --no-verify`.",
                    style="dim",
                ),
            ),
            border_style="green",
            expand=False,
        )
    )
    return 0


def _normalize_block_on(value: str) -> str:
    upper = value.strip().upper()
    if upper not in SEVERITY_ORDER:
        raise click.BadParameter(
            f"must be one of CRITICAL, HIGH, MEDIUM, LOW (got {value!r})",
            param_hint="--block-on",
        )
    return upper


def _exceeds_block_threshold(counts: dict[str, int], block_on: str) -> bool:
    threshold = SEVERITY_ORDER[block_on]
    for severity, count in counts.items():
        if count and SEVERITY_ORDER.get(severity, 99) <= threshold:
            return True
    return False


def _emit_machine_document(
    reports: list[FileReport],
    target: Path,
    stats: RunStats,
    output_format: str,
) -> None:
    """Write the chosen machine-readable document to stdout."""
    if output_format == "json":
        document = to_json(
            reports,
            target=target,
            files_scanned=stats.files_scanned,
            files_analyzed=stats.files_analyzed,
            files_failed=stats.files_failed,
            files_skipped=stats.files_skipped,
        )
    elif output_format == "sarif":
        document = to_sarif(
            reports,
            files_scanned=stats.files_scanned,
            files_analyzed=stats.files_analyzed,
            files_failed=stats.files_failed,
        )
    elif output_format == "markdown":
        document = to_markdown(
            reports,
            target=target,
            files_scanned=stats.files_scanned,
            files_analyzed=stats.files_analyzed,
            files_failed=stats.files_failed,
        )
    else:  # pragma: no cover - guarded by click.Choice
        raise ValueError(f"Unknown machine output format: {output_format!r}")
    sys.stdout.write(document)
    sys.stdout.write("\n")
    sys.stdout.flush()


def _block_counts_for_exit(
    reports: list[FileReport],
    in_diff_mode: bool,
) -> dict[str, int]:
    """Aggregate counts that govern the exit code.

    Mirrors what _render_summary would have returned: in diff mode we only block
    on findings introduced by the diff (pre-existing findings warn but don't gate),
    matching the terminal-mode behavior.
    """
    counts: dict[str, int] = {sev: 0 for sev in SEVERITY_ORDER}
    for report in reports:
        for finding in report.findings:
            if in_diff_mode and finding.pre_existing:
                continue
            counts[finding.severity] = counts.get(finding.severity, 0) + 1
    return counts


@click.command()
@click.argument(
    "path",
    required=False,
    default=".",
    type=click.Path(exists=True, path_type=Path, readable=True),
)
@click.option(
    "--model",
    default=DEFAULT_MODEL,
    show_default=True,
    help="Anthropic model to use for analysis.",
)
@click.option(
    "--prefilter/--no-prefilter",
    "use_prefilter",
    default=True,
    show_default=True,
    help=(
        "Run a fast Semgrep pass first and only deep-reason on files Semgrep "
        "flagged. Falls back automatically if the semgrep binary is missing."
    ),
)
@click.option(
    "--diff",
    "diff_ref",
    is_flag=False,
    flag_value=DIFF_DEFAULT_SENTINEL,
    default=None,
    help=(
        "Scan only files changed in git. With no value: staged + unstaged vs HEAD. "
        "With a ref: files changed in <ref>...HEAD."
    ),
)
@click.option(
    "--staged",
    is_flag=True,
    default=False,
    help="With --diff, restrict to staged changes only (suitable for pre-commit hooks).",
)
@click.option(
    "--block-on",
    "block_on",
    default="HIGH",
    show_default=True,
    callback=lambda ctx, param, value: _normalize_block_on(value),
    help=(
        "Severity threshold for a non-zero exit. CRITICAL = block only on critical "
        "findings; HIGH = block on critical+high; etc. Honored after env var "
        "VULNSCAN_BLOCK_SEVERITY if set."
    ),
)
@click.option(
    "--install-hook",
    "install_hook",
    is_flag=True,
    default=False,
    help="Write a pre-commit hook to .git/hooks/pre-commit and exit.",
)
@click.option(
    "--format",
    "output_format",
    type=click.Choice(OUTPUT_FORMATS, case_sensitive=False),
    default="terminal",
    show_default=True,
    help=(
        "Output format. `terminal` renders the colored human report. "
        "`json` emits a stable JSON document on stdout. `sarif` emits SARIF 2.1.0 "
        "for GitHub code scanning and other dashboards. `markdown` emits a "
        "compact summary suitable for a sticky PR comment. Non-terminal formats "
        "send all status output to stderr."
    ),
)
@click.version_option(__version__, prog_name="vulnscan")
def main(
    path: Path,
    model: str,
    use_prefilter: bool,
    diff_ref: str | None,
    staged: bool,
    block_on: str,
    install_hook: bool,
    output_format: str,
) -> None:
    """Audit PATH (a file or directory; defaults to .) for security vulnerabilities."""
    output_format = output_format.lower()
    machine_mode = output_format != "terminal"

    # Route all human-facing output (banner, panels, dim notes, spinners, errors)
    # to stderr when emitting a machine-readable document, so stdout contains
    # only the document and stays pipeable to `jq` and friends. Always rebind
    # on entry so multiple in-process invocations don't leak state.
    global console
    console = Console(file=sys.stderr) if machine_mode else Console()

    if not machine_mode:
        _banner()

    if install_hook:
        sys.exit(_install_pre_commit_hook(path))

    # Env-var override for block threshold (pre-commit hook reads VULNSCAN_BLOCK_SEVERITY).
    env_block = os.environ.get("VULNSCAN_BLOCK_SEVERITY")
    if env_block:
        try:
            block_on = _normalize_block_on(env_block)
        except click.BadParameter as exc:
            console.print(f"[bold red]Error:[/bold red] {exc.message}")
            sys.exit(2)

    stats = RunStats()
    diff_payload: DiffInfo | None = None

    if diff_ref is not None:
        ref = None if diff_ref == DIFF_DEFAULT_SENTINEL else diff_ref
        scope = "staged" if staged else ("ref " + ref if ref else "staged + unstaged vs HEAD")
        try:
            diff_payload = diff_info(path, ref=ref, staged_only=staged)
        except GitError as exc:
            console.print(f"[bold red]Error:[/bold red] {exc}")
            sys.exit(2)
        sources = _diff_sources(diff_payload)
        stats.diff_mode_note = (
            f"Diff mode: {scope}; {len(diff_payload.changed_files)} changed file(s) "
            f"({len(sources)} scannable)."
        )
        if not sources:
            console.print(f"[dim]{stats.diff_mode_note}[/dim]")
            console.print("[dim]No scannable changes — nothing to do.[/dim]")
            if machine_mode:
                # Emit an empty-but-valid document so CI uploaders (SARIF, comment
                # poster) never see a missing file on a no-op PR.
                _emit_machine_document([], path, RunStats(), output_format)
            sys.exit(0)
    elif staged:
        console.print("[bold red]Error:[/bold red] --staged requires --diff.")
        sys.exit(2)
    else:
        sources = list(discover(path))
        if not sources:
            console.print("[yellow]No supported source files found.[/yellow]")
            if machine_mode:
                _emit_machine_document([], path, RunStats(), output_format)
            sys.exit(0)

    stats.files_scanned = len(sources)

    prefilter_active, prefilter_result, prefilter_note = _prefilter_decision(
        path, use_prefilter
    )
    stats.prefilter_active = prefilter_active
    stats.prefilter_note = prefilter_note
    if prefilter_note:
        console.print(f"[dim]{prefilter_note}[/dim]")
    if stats.diff_mode_note:
        console.print(f"[dim]{stats.diff_mode_note}[/dim]")

    try:
        analyzer = Analyzer(model=model)
    except AnalyzerError as exc:
        console.print(f"[bold red]Error:[/bold red] {exc}")
        sys.exit(2)

    if prefilter_active and prefilter_result is not None:
        flagged_paths = {p for p, hits in prefilter_result.hits_by_file.items() if hits}
        stats.files_flagged_by_semgrep = len(flagged_paths)
        console.print(
            f"[dim]Discovered {len(sources)} file(s); Semgrep flagged "
            f"{stats.files_flagged_by_semgrep}. Deep-reasoning with {model}…[/dim]\n"
        )
    else:
        console.print(
            f"[dim]Discovered {len(sources)} file(s). Analyzing with {model}…[/dim]\n"
        )

    reports: list[FileReport] = []
    for source in sources:
        leads = None
        if prefilter_active and prefilter_result is not None:
            leads = prefilter_result.hits_for(source.path)
            if not leads:
                continue
        changed_ranges = None
        if diff_payload is not None:
            try:
                resolved = source.path.resolve()
            except OSError:
                resolved = source.path
            changed_ranges = diff_payload.ranges_by_file.get(resolved)
        stats.files_sent_to_api += 1
        try:
            with console.status(f"Analyzing {source.path}…", spinner="dots"):
                report = analyzer.analyze(source, leads=leads, changed_ranges=changed_ranges)
        except AuthError as exc:
            console.print(
                f"[bold red]Authentication error:[/bold red] {exc}\n\n"
                "The API key is invalid or expired. Set a valid key and retry:\n"
                "  PowerShell:  [bold]$env:ANTHROPIC_API_KEY = \"sk-ant-...\"[/bold]\n"
                "  Bash/zsh:    [bold]export ANTHROPIC_API_KEY=\"sk-ant-...\"[/bold]"
            )
            sys.exit(2)
        reports.append(report)
        if not machine_mode:
            _render_file_report(report)

    stats.api_request_count = analyzer.request_count
    stats.files_analyzed = sum(1 for r in reports if r.outcome == "analyzed")
    stats.files_failed = sum(1 for r in reports if r.outcome == "failed")
    stats.files_skipped = stats.files_scanned - stats.files_sent_to_api

    if machine_mode:
        _emit_machine_document(reports, path, stats, output_format)
        blocking_counts = _block_counts_for_exit(reports, in_diff_mode=bool(stats.diff_mode_note))
    else:
        blocking_counts = _render_summary(reports, stats)

    # Exit-code priority: 2 (config/auth) already handled above.
    # 1 — findings at or above block threshold (gate); 3 — inconclusive (some
    # files failed, can't confirm clean); 0 — all analyzed, nothing blocking.
    if _exceeds_block_threshold(blocking_counts, block_on):
        sys.exit(1)
    if stats.files_failed:
        sys.exit(3)
    sys.exit(0)


if __name__ == "__main__":
    main()
